homework-functions
os-spirit/aqa-advanced-2 pull request #4
Opened 2023-10-24 15:18 UTC by os-spirit

- This PR contains homework on functions.
- All works are marked by number (1,2,3,4)
- Each task is contained in a separate file

2023-10-24 19:55 UTC, sttaran requested changes

2023-10-24 19:55 UTC, sttaran commented on js_basics/homework_functions/task1.js
> +function rectangleArea(width, height) {
function name should represent the action e.g. `calculateRectangleArea`, `getRectangleArea` etc

2023-10-24 19:55 UTC, sttaran commented on js_basics/homework_functions/task1.js
> +    console.log(rectangleAreaResult);
please return the value from the function

2023-10-24 19:55 UTC, sttaran commented on js_basics/homework_functions/task2.js
> +function isAdult (age) {
you can make it easier 
```js
function isAdult (age) {
    return age >= 18
}
```

2023-10-25 07:53 UTC, os-spirit commented on js_basics/homework_functions/task2.js
> +function isAdult (age) {
Added minor improvements:
- Changed variable names in the first task
- Added return from a function when declaring it
- Console log is displayed outside the function (now it is when calling the function)
- Removed true / false keywords in the second task
[You can see these here](https://github.com/os-spirit/aqa-advanced-2/pull/4/commits/5ec85420b2b6b0829daeeca0951538f5b9e43c97)

2023-10-25 09:13 UTC, sttaran approved these changes

2023-10-26 08:29 UTC, merged